addons:
  apt:
    packages:
    - libmp3lame-dev
    - libopus-dev
    - libvpx-dev
    - libx264-dev
    - yasm
  homebrew:
    packages:
    - ffmpeg
    - opus
    - libvpx
    update: true
cache:
  directories: $HOME/.local
  pip: true
dist: xenial
env:
  global:
    - CIBW_BEFORE_BUILD=".travis/build-codecs"
    - CIBW_ENVIRONMENT="CFLAGS=-I/tmp/aiortc.deps/include LDFLAGS=-L/tmp/aiortc.deps/lib LD_LIBRARY_PATH=/tmp/aiortc.deps/lib PKG_CONFIG_PATH=/tmp/aiortc.deps/lib/pkgconfig"
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - CIBW_TEST_COMMAND="python3 -m unittest discover -s {project}/tests"
install: source .travis/install
language: python
matrix:
  include:
  - env: BUILD=lint
    install: pip install black flake8 isort
    python: "3.6"
  - env: BUILD=test
    language: generic
    os: osx
  - env: BUILD=test
    python: "3.8"
  - env: BUILD=test CRYPTOGRAPHY_NO_BINARY=1
    python: "3.8"
  - env: BUILD=test
    python: "3.7"
  - env: BUILD=test CRYPTOGRAPHY_NO_BINARY=1
    python: "3.7"
  - env: BUILD=test
    python: "3.6"
  - env: BUILD=test CRYPTOGRAPHY_NO_BINARY=1
    python: "3.6"
  - env: BUILD=test
    python: "3.5"
    dist: trusty
  - env: BUILD=test CRYPTOGRAPHY_NO_BINARY=1
    dist: trusty
    python: "3.5"
  - env: BUILD=wheel
    install: pip install cibuildwheel
  - env: BUILD=sdist
    install: pip install twine
    python: "3.6"
script: .travis/script
sudo: true
